### ISSUE TITLE
Font is always the same size.

### ISSUE THREAD

**Issue by littlethormanator** [exyte/SVGView#16]
When I render an svgs, the font is always the same size. I have a number of svgs images that have fonts of different size in them, but when rendered with SVGView, they are all the same size. Below are a couple of pictures from an example.

What the svgs should actually look like.
<img width="476" alt="Screen Shot 2022-05-25 at 4 35 24 AM" src="https://user-images.githubusercontent.com/76926186/170253223-fde42f0e-aafe-4a88-a04d-063596fc21b9.png">

What the svgs looks like with SVGView.
<img width="308" alt="Screen Shot 2022-05-25 at 4 36 44 AM" src="https://user-images.githubusercontent.com/76926186/170253232-277184d8-5b64-44e0-a073-92683f14d9b2.png">

Here is the actual svgs file that I used for this example.
![FontExample](https://user-images.githubusercontent.com/76926186/170253922-d1915683-d8fb-4750-84c4-230fb4719b22.svg)

**Comment by ystrot** [comment]
Hi @littlethormanator,

Thanks for reporting! Will check it out.

**Comment by ystrot** [comment]
Fixed in the 1.0.4 release.
