### ISSUE TITLE
how to change svg color?

### ISSUE THREAD

**Issue by iworkcloud** [exyte/SVGView#22]
Transparency can be modified, but how to change svg color?

**Comment by GDGapps** [comment]
```
if view.getNode(byId: name) != nil {
                
                let nodeShape = view.getNode(byId: country.name) as! SVGShape
                nodeShape.fill = SVGColor(r: 19, g: 200, b: 66)
            }
```

**Comment by iworkcloud** [comment]
Thank you！it ok!

**Comment by martinkaplan** [comment]
hi im trying set color to the node
this answer looks promising but im not able to cast it to SVGShape


  let view = SVGView(contentsOf: url)
  if let part = view.getNode(byId:"xxx") as? SVGShape {
      part.fill = SVGColor(hex: "FF000088")
  }


can anyone give me some suggestion how to cast SVGNode to a shape? (as? is not working)

**Comment by martinkaplan** [comment]
<img width="337" alt="Screenshot 2023-08-10 at 12 47 00" src="https://github.com/exyte/SVGView/assets/612440/f14a538f-be8b-4cbd-95ff-a96522e11ef1">

**Comment by ystrot** [comment]
I mean SVG file itself. You can show the whole file or only part with your xxx node.

**Comment by martinkaplan** [comment]
oh sure, im not experienced with svg images ... so no clue what im doing wrong 

`<svg height="100%" viewBox="0 0 652 1200" fill="none" xmlns="http://www.w3.org/2000/svg">
<g id="hamstrings" class="body-map__muscle">
<path d="M445.184 807.888C446.787 801.789 448.155 795.533 449.322 789.172L449.314 789.164C465.006 703.905 443.772 599.686 435.564 575.803C431.113 562.86 431.356 559.172 431.634 554.931L431.635 554.927C431.641 554.821 431.647 554.715 431.654 554.609C431.719 553.54 431.787 552.428 431.739 551.049V550.997C430.38 539.609 417.432 527.898 403.996 519.743C409.562 527.112 412.133 536.561 415.172 547.736L415.175 547.747L415.363 548.427C416.558 552.771 417.791 557.25 419.314 562.019C427.627 587.984 426.773 608.53 416.814 623.099C404.85 640.569 383.416 643.679 374.764 644.219C373.509 644.289 372.245 644.376 371.008 644.464C370.834 644.481 370.642 644.498 370.468 644.498C370.113 644.534 369.758 644.553 369.397 644.573C369.227 644.582 369.056 644.592 368.882 644.603C367.201 644.725 365.536 644.829 363.881 644.917H363.741C360.352 645.23 357.163 645.927 355.464 647.853C354.279 649.186 353.808 651.103 354 653.726C355.307 670.633 351.554 677.779 347.922 684.695L347.913 684.71C343.332 693.446 339.007 701.693 345.766 730.951C347.108 735.909 348.458 740.718 349.8 745.484C353.852 759.896 357.764 773.855 361.171 790.227C361.572 790.488 361.851 790.906 361.92 791.394C369.135 840.38 376.863 860.368 388.6 860.368C401.827 860.368 402.576 837.165 403.012 823.311C403.291 814.275 403.413 810.537 406.088 810.067C408.423 809.683 410.296 811.452 417.458 829.497C423.226 844.039 427.557 845.799 429.604 845.538C435.294 844.858 440.592 830.569 444.434 814.807C444.469 812.376 444.713 810.075 445.184 807.888Z" fill="currentColor"></path>
</svg>`

**Comment by ystrot** [comment]
Basically, you have a path element inside: `<path d="..." fill="currentColor">` which is actually your shape. If you want to change it, you need to give it some id. Like this: `<path id="xxx" d="..." fill="currentColor">`

After that your code will make sense. Right now there is just no "xxx" element.

**Comment by martinkaplan** [comment]
like xxx is just placeholder i have all the id=CONSTANTS in array and checking them in loop and i want asign diferent colors... finding node is not problem but casting node to the  SVGShape is problem 
so no issue with svg file it self?

**Comment by ystrot** [comment]
The only element which have id in your SVG is <g>, i.e. group element. So it's not a SVGShape. You could rather add id to a <path> as I mentioned above, or you can do something like this:

```Swift
if let group = view.getNode(byId:"hamstrings") as? SVGGroup {
  for content in group.contents {
    if let shape = content as? SVGShape {
      shape.fill = SVGColor(hex: "FF000088")
    }
  }  
}
```

**Comment by martinkaplan** [comment]
got it now thank you so much
