### ISSUE TITLE
Could you please create a new release tag (1.0.5)?

### ISSUE THREAD

**Issue by ba01ei** [exyte/SVGView#44]
Hi @f3dm76 I saw that you've merged a few pull requests in May, thanks a lot!

Could you please also create a new release tag (1.0.5) which points to the latest main branch? The latest tag right now is 1.0.4 created in June 2022: https://github.com/exyte/SVGView/tags

Thanks.

**Comment by f3dm76** [comment]
@ba01ei, all done, have a great day!
